server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/

spring:
  application:
    name: eureka-client
  profiles: client3

---
server:
  port: 8764

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/

spring:
  application:
    name: eureka-client
  profiles: client4