server:
  port: 8761
spring:
  application:
    name: eureka-server
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    #    表示是否注册自身到eureka服务器
    register-with-eureka: false
    #    是否从eureka上获取注册信息
    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
#为了测试方便将peer2:8762改为 peer1:8761
---
server:
  port: 8762
spring:
  application:
    name: eureka-server
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    #    表示是否注册自身到eureka服务器
    #    register-with-eureka: false
    #    是否从eureka上获取注册信息
    #    fetch-registry: false
    service-url:
      default-zone: http://peer1:8761/eureka/

#修改host 添加 127.0.0.1 peer1和peer2
#启动类自己加个peer2的 active分别填写peer1和peer2